data:
  root: "./datasets/UIEB/"
  train_dir: "train"
  test_dir: "test"
  input_dir: "raw"
  target_dir: "reference"  
  image_size: 256
  max_len: 1  

model:
  inp_channels: 3
  out_channels: 3
  d: 20                  
  num_blocks: [2, 2, 2, 3] 
  num_refinement: 4       
  heads: [2, 4, 8, 16]    
  ffn_exp: 2.0          
  
  loss_cfg:
    weights:
      l1: 1.0
      perc: 0.05
      ssim: 2.0
      grad: 0.8              

training:
  model_dir: "./outputs_UIEB"
  warmup_epochs: 15       
  gradient_clip: 1.0     

  optimization:
    optimizer:
      name: "AdamW"
      lr: 0.0002      
      weight_decay: 0.0001
      betas: [0.9, 0.999]

    scheduler:
      name: "CosineAnnealingLR"
      T_max: 1000
      eta_min: 0.00001

evaluation:
  metrics: ["psnr", "ssim", "lpips"]
  save_images: true
  save_high_res: false 