data:
  root: "./datasets/UIEB/"
  train_dir: "train"
  test_dir: "test"
  input_dir: "raw"
  target_dir: "reference"  
  image_size: 256
  batch_size: 4
  num_workers: 4
  max_len: 1  

model:
  inp_channels: 3
  out_channels: 3
  d: 36                    
  num_blocks: [2, 2, 2, 3] 
  num_refinement: 2       
  heads: [1, 2, 2, 4]    
  ffn_exp: 2.0          
  
  loss_cfg:
    weights:
      l1: 1.0              
      perc: 0.02           
      ms_ssim: 0.5         
      phys: 0.8            
      grad: 0.1            
      tv: 0.0001          
    perc_layers: ["relu3_3", "relu4_3"] 
    ms_window_size: 11    
    ms_window_sigma: 1.5  
    use_tv_on_t: true     

training:
  model_dir: "./outputs/UIEB/"
  epochs: 800
  batch_size: 4
  learning_rate: 0.0003
  weight_decay: 0.0001
  warmup_epochs: 5
  save_freq: 10
  eval_freq: 5
  print_freq: 100
  gradient_clip: 1.0  # Add gradient clipping to prevent exploding gradients

  optimization:
    optimizer:
      name: "AdamW"
      lr: 0.0003
      weight_decay: 0.0001
      betas: [0.9, 0.999]

    scheduler:
      name: "CosineAnnealingLR"
      T_max: 800
      eta_min: 0.00001

evaluation:
  metrics: ["psnr", "ssim", "lpips"]
  save_images: true
  save_high_res: false 