data:
  root: "./datasets/UIEB/"
  train_dir: "train"
  test_dir: "test"
  input_dir: "raw"
  target_dir: "reference"  
  image_size: 256
  batch_size: 4
  num_workers: 4
  max_len: 1  

model:
  # UIE_model parameters
  inp_channels: 3
  out_channels: 3
  d: 36                    # base channel dimension
  num_blocks: [2, 2, 2, 3] # encoder blocks per level
  num_refinement: 2        # refinement blocks
  heads: [1, 2, 2, 4]     # attention heads per level
  ffn_exp: 2.0            # FFN expansion factor
  
  # Loss configuration
  loss_cfg:
    weights:
      l1: 1.0              # reconstruction loss weight
      perc: 0.02           # perceptual loss weight
      ms_ssim: 0.5         # MS-SSIM loss weight
      phys: 0.8            # physics consistency weight
      grad: 0.1            # gradient loss weight
      tv: 0.0001          # total variation weight (fixed from string)
    perc_layers: ["relu3_3", "relu4_3"]  # VGG layers for perceptual loss
    ms_ssim_levels: 5     # MS-SSIM levels
    ms_window_size: 11    # MS-SSIM window size
    ms_window_sigma: 1.5  # MS-SSIM window sigma
    use_tv_on_t: true     # apply TV regularization on transmission

training:
  model_dir: "./outputs/UIEB/"
  epochs: 800
  batch_size: 4
  learning_rate: 0.0003
  weight_decay: 0.0001
  warmup_epochs: 5
  save_freq: 10
  eval_freq: 5
  print_freq: 100
  
  optimization:
    optimizer:
      name: "AdamW"
      lr: 0.0003
      weight_decay: 0.0001
      betas: [0.9, 0.999]
    
    scheduler:
      name: "CosineAnnealingLR"
      T_max: 800
      eta_min: 0.00001

evaluation:
  metrics: ["psnr", "ssim", "lpips"]
  save_images: true
  save_high_res: false 